# Generated by Django 2.2.4 on 2020-07-06 04:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('code', models.AutoField(default='', primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=150)),
                ('author', models.CharField(max_length=50)),
                ('translator', models.CharField(default='', max_length=50, null=True)),
                ('isbn', models.CharField(default='', max_length=13, null=True)),
                ('page', models.IntegerField(default=0, null=True)),
                ('publisher', models.CharField(default='', max_length=50, null=True)),
                ('publishdate', models.DateField(null=True)),
                ('created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('code', models.CharField(default='', max_length=21, primary_key=True, serialize=False)),
                ('content', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='book_covers/')),
                ('created', models.DateTimeField(null=True)),
                ('code', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
            ],
        ),
        migrations.CreateModel(
            name='Book_Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catecode', models.CharField(max_length=21)),
                ('bookcode', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
            ],
        ),
    ]
