# Generated by Django 2.2.4 on 2020-06-24 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(default='', max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publishdate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='publisher',
            field=models.CharField(default='', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='translator',
            field=models.CharField(default='', max_length=50, null=True),
        ),
    ]
