# Generated by Django 2.2.4 on 2020-07-06 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcover',
            name='id',
        ),
        migrations.AlterField(
            model_name='bookcover',
            name='code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='Book.Book'),
        ),
    ]
