# Generated by Django 2.2.4 on 2020-06-26 05:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0004_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book_Cate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
                ('catecode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Category')),
            ],
        ),
    ]
