# Generated by Django 2.2.4 on 2020-06-26 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0005_book_cate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cate',
            name='catecode',
            field=models.CharField(max_length=15),
        ),
    ]
