# Generated by Django 2.2.4 on 2020-06-26 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0006_auto_20200626_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book_cate',
            name='bookcode',
            field=models.IntegerField(),
        ),
    ]
