# Generated by Django 2.2.4 on 2020-07-06 01:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Book', '0007_auto_20200626_0941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='modified',
        ),
        migrations.CreateModel(
            name='BookCover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cover', models.ImageField(upload_to='book_covers/')),
                ('created', models.DateTimeField(null=True)),
                ('bookcode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Book.Book')),
            ],
        ),
    ]
