# Generated by Django 2.2.4 on 2020-09-24 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('pw', models.CharField(max_length=70)),
                ('email', models.CharField(default='', max_length=50, null=True, unique=True)),
                ('nickname', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('created', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Member_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Book_code', models.IntegerField(default=0)),
                ('state', models.CharField(max_length=20)),
                ('rating', models.IntegerField(default=0, null=True)),
                ('created', models.DateTimeField(null=True)),
                ('Member_id', models.ForeignKey(default='remove_member', on_delete=django.db.models.deletion.SET_DEFAULT, to='Member.Member')),
            ],
        ),
    ]
